#
# Enterprise MongoDB for Kubernetes.
#

# Set this to true if your cluster is managing SecurityContext for you.
# If running OpenShift (Cloud, Minishift, etc.), set this to true.
managedSecurityContext: false

operator:
  # Execution environment for the operator, dev or prod. Use dev for more verbose logging
  env: dev 

  # Name that will be assigned to most of internal Kubernetes objects like Deployment, ServiceAccount, Role etc.
  name: mongodb-enterprise-operator

  # Version of mongodb-enterprise-operator and mongodb-enterprise-database images
  version: latest

database:
  name: mongodb-enterprise-database


appDb:
  name: mongodb-enterprise-appdb

registry:
  # Specify if images are pulled from private repository
  imagePullSecrets:
  pullPolicy: Always
  repository: quay.io/mongodb

# Set this to true if the operator will require Kubernetes CA
# infrastructure to generate TLS certificates.
needsCAInfrastructure: true


opsManager:
  image: mongodb-enterprise-ops-manager
  enabled: true
  port: 8080
  adminCredentials:
    FirstName: Joe
    LastName: McMongo
    Password: MongoDB12345% 
    Username: admin@mongodb.com
    publicApiKey: MongoDB12345%

mongodb:
  cluster:
    members: 3
    clusterDomain: cluster.local
    version: 4.2.3-ent
    #version: 4.2.3

# add users:

