apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    product: {{ .Chart.Name }}
spec:
  members: {{ .Values.mongodb.cluster.members }}
  type: ReplicaSet
  version: {{ .Values.mongodb.cluster.version }}
  clusterDomain: {{ .Values.mongodb.cluster.clusterDomain }}
  service: {{ .Release.Name }}
  opsManager:
    configMapRef:
      name: {{ .Release.Name }}-ops-manager-project
  credentials: {{ .Release.Name }}-ops-manager-admin-key
  logLevel: WARN
  persistent: true
  podSpec:
    cpu: '0.5'
    memory: 1G
    persistence:
      single:
        storage: 10G   
        #storageClass: default 
