apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ui
  namespace: {{ .Release.Namespace }} 
spec:
  replicas: 1
  selector:
      matchLabels:
        app: {{ .Release.Name }}-ui
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ui
    spec:
      serviceAccountName: mongodb-enterprise-operator
      containers:
      - name: mongodb-k8s-ui 
        image: jmimick/mongodb-k8s-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
