apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-workload
  namespace: {{ .Release.Namespace }} 
data: 
  workload: | 
{{ .Values.workloadDefaults | indent 4 }}
{{- range $key, $value := .Values.workload }}
    # workload overrides
{{ $key | indent 4 }}={{ $value }}
{{- end }}
