action: "load"   # Or "run"
binding:  

parallelism: 1

workloadDefaults: |+ 
  recordcount={{ .Values.recordCount | default 10000 }}
  operationcount={{ .Values.operationCount | default 100000 }}
  workload=site.ycsb.workloads.CoreWorkload

  readallfields=true

  readproportion=0.5
  updateproportion=0.5
  scanproportion=0
  insertproportion=0

  requestdistribution=zipfian

  table=ycsb
